/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.betteru.betteru;

//import static com.mycompany.betteru.betteru.SetReminder.dateTime;
//import static com.mycompany.betteru.betteru.SetReminder.task;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    String LoggedInUser = null;

    public MainMenu(String User) {
        initComponents();
        Color color = new Color(245, 245, 220);
        getContentPane().setBackground(color);
        LoggedInUser = User;
        userLabel.setText(LoggedInUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openCalorieCalculator = new javax.swing.JButton();
        openCalorieTracker = new javax.swing.JButton();
        openRandomQuote = new javax.swing.JButton();
        openReminder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        openBmiCalculator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        openCalorieCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calorie_Calculator.png"))); // NOI18N
        openCalorieCalculator.setText("Calorie Calculator");
        openCalorieCalculator.setFocusPainted(false);
        openCalorieCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCalorieCalculatorActionPerformed(evt);
            }
        });

        openCalorieTracker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calorie_Tracker.png"))); // NOI18N
        openCalorieTracker.setText("Calorie Tracker");
        openCalorieTracker.setFocusPainted(false);
        openCalorieTracker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCalorieTrackerActionPerformed(evt);
            }
        });

        openRandomQuote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quote.png"))); // NOI18N
        openRandomQuote.setText("Random Quote");
        openRandomQuote.setFocusPainted(false);
        openRandomQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRandomQuoteActionPerformed(evt);
            }
        });

        openReminder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reminder.png"))); // NOI18N
        openReminder.setText("Reminder");
        openReminder.setFocusPainted(false);
        openReminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openReminderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome!");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Habbit_Tracker.png"))); // NOI18N
        jButton1.setText("Habbit Tracker");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stats.png"))); // NOI18N
        jButton2.setText("*Stats & Suggestions*");
        jButton2.setFocusPainted(false);

        jLabel2.setText("Logged in User:");

        userLabel.setText("jLabel3");

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        openBmiCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMI_Calculator.png"))); // NOI18N
        openBmiCalculator.setText("BMI Calculator");
        openBmiCalculator.setFocusPainted(false);
        openBmiCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBmiCalculatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openReminder, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openBmiCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(openCalorieCalculator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(openCalorieTracker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openRandomQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(userLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(openBmiCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openCalorieTracker, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(openCalorieCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openReminder, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(openRandomQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openCalorieCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCalorieCalculatorActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalorieCalculator(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_openCalorieCalculatorActionPerformed

    private void openRandomQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRandomQuoteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuoteAPI(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_openRandomQuoteActionPerformed

    private void openReminderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openReminderActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetReminder(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_openReminderActionPerformed

    private void openCalorieTrackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCalorieTrackerActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalorieTracker(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_openCalorieTrackerActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to Logout?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            LoggedInUser = "";
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Login().setVisible(true);
                }
            });
            dispose();
        } else {
            // User clicked "No" or closed the dialog box
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabbitTracker(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openBmiCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBmiCalculatorActionPerformed
            // openBmiCalculator.setMargin(new Insets(0, 0, 0, 0));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorBMI(LoggedInUser).setVisible(true);
            }
        });
    }//GEN-LAST:event_openBmiCalculatorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton openBmiCalculator;
    private javax.swing.JButton openCalorieCalculator;
    private javax.swing.JButton openCalorieTracker;
    private javax.swing.JButton openRandomQuote;
    private javax.swing.JButton openReminder;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
